sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  global:
     - LD_LIBRARY_PATH=/usr/lib/llvm-3.7/lib
before_install:
  - curl http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -y
  - sudo apt-get install libclang-3.7-dev -y
install:
  - "pip install --process-dependency-links ."
script:
  - "python setup.py test"
